services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/database/data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  directus:
    image: directus/directus:11.10.0
    container_name: directus
    restart: always
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
    depends_on:
      - postgres
    environment:
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      STORAGE_LOCATIONS: digitalocean
      STORAGE_DIGITALOCEAN_DRIVER: s3
      STORAGE_DIGITALOCEAN_ROOT: /assets-production
      STORAGE_DIGITALOCEAN_KEY: ${DO_KEY}
      STORAGE_DIGITALOCEAN_SECRET: ${DO_SECRET}
      STORAGE_DIGITALOCEAN_ENDPOINT: https://nyc3.digitaloceanspaces.com
      STORAGE_DIGITALOCEAN_BUCKET: oooo-assets
      STORAGE_DIGITALOCEAN_REGION: us-east-1
      MAX_PAYLOAD_SIZE: 20mb
    ports:
      - "8055:8055"

  astro:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: astro
    volumes:
      - ./app/public/assets/leporello_files:/app/public/assets/leporello_files
    ports:
      - "4321:4321"
    environment:
      VITE_DIRECTUS_URL: http://directus:8055
    depends_on:
      - directus